name: Run Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOSECGOVERSION: go1.23.2
      GOTOOLCHAIN: go1.23.2
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
